version: "3.8"
services: 
    
    # mssql
    mssql:
        container_name: mssql
        image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
        ports:
            - 9004:1433
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: Test123456!
            TZ: Asia/Bangkok
        restart: always

    # PostgreSQL 13.0
    postgresql:
        container_name: postgresql
        build: ./postgresql
        ports:
            - 9003:5432
        volumes:
            - ./postgresql/volumes:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 12345678
            # POSTGRES_USER: 
            # POSTGRES_DB:
            # POSTGRES_INITDB_ARGS:
            # POSTGRES_INITDB_WALDIR:
            # POSTGRES_HOST_AUTH_METHOD:
            # PGDATA:
            TZ: Asia/Bangkok
        restart: always

    # mongo 4.4.1
    mongo:
        container_name: mongoDB
        build: ./mongo
        ports:
            - 9002:27017
        volumes:
            - ./mongo/volumes:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12345678
            TZ: Asia/Bangkok
        restart: always

    # mysql 8.0.22
    mysql:
        container_name: mysql
        build: ./mySQL
        ports:
            - 9001:3306
        volumes:
            - ./mySQL/volumes:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_USER: user
            MYSQL_PASSWORD: 12345678
            # MYSQL_DATABASE:
            TZ: Asia/Bangkok
        restart: always

    portainer:
        container_name: portainer
        image: portainer/portainer
        ports:
            - 9000:9000
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            TZ: Asia/Bangkok
        restart: always

networks:
    default:
        external:
            name: DB-Networks